include catppuccin-mocha.conf

mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click link

background_image /home/michael/Pictures/Wallpapers/YorForger.jpg
background_image_layout cscaled
background_image_linear no
background_tint 0.9
background #000000

tab_bar_edge top
tab_bar_style fade
