fullName: "Ngô Văn Cảnh"
nickName: "Michael"
userName: "canh25xp"
knoxID: "vancanh.ng"
themeName: "Catppuccin"
themeFlavor: "Mocha"
themeAccent: "Pink"
nerdfontName: "CaskaydiaMonoNerdFont-Regular.ttf"
nerdfontDisplayName: "CaskaydiaMono Nerd Font"
emailPersonal: "nv.canh@outlook.com"
emailWork: "vancanh.ng@samsung.com"

# Termux
phoneUserName: "u0_a505"
tabletUserName: "u0_a353"
phoneDeviceName: "bunnies-f741b"
tabletDeviceName: "bunnies-x826b"

# Local ip address
desktopIPv4: 192.168.0.100
laptopIPv4: 192.168.0.101
phoneIPv4: 192.168.0.102

# Tailscale
tailnetDNS: "walleye-godzilla.ts.net"
desktopTailscale: "bunnies-desktop"
desktopTailscaleIP: 100.99.0.0

laptopTailscale: "bunnies-laptop"
laptopTailscaleIP: 100.99.0.1

phoneTailscale: "bunnies-f741b"
phoneTailscaleIP: 100.99.0.2

tabletTailscale: "bunnies-x826b"
tabletTailscaleIP: 100.99.0.3
