fullName: "Ngô Văn Cảnh"
nickName: "Michael"
userName: "canh25xp"
themeName: "Catppuccin"
themeFlavor: "Mocha"
themeAccent: "Pink"
nerdfontName: "CaskaydiaMonoNerdFont-Regular.ttf"
nerdfontDisplayName: "CaskaydiaMono Nerd Font"
emailPersonal: "nv.canh@outlook.com"
emailWork: "vancanh.ng@samsung.com"

# Termux
phoneUserName: "u0_a505"
tabletUserName: "u0_a353"
