fullName: "Ngô Văn Cảnh"
nickName: "Michael"
userName: "canh25xp"
themeName: "Catppuccin"
themeFlavor: "Mocha"
themeAccent: "Pink"
nerdfontName: "CaskaydiaMonoNerdFont-Regular.ttf"
nerdfontDisplayName: "CaskaydiaMono Nerd Font"
emailPersonal: "nv.canh@outlook.com"
emailWork: "vancanh.ng@samsung.com"

# Termux
phoneUserName: "u0_a505"
tabletUserName: "u0_a353"
phoneDeviceName: "bunnies-f741b"
tabletDeviceName: "bunnies-x826b"

# Local ip address
desktopIPv4: 192.168.0.100
laptopIPv4: 192.168.0.101
phoneIPv4: 192.168.0.102
