fullName: "Ngô Văn Cảnh"
nickName: "Michael"
userName: "canh25xp"
knoxID: "vancanh.ng"
themeName: "Catppuccin"
themeFlavor: "Mocha"
themeAccent: "Pink"
nerdfontName: "CaskaydiaMonoNerdFont-Regular.ttf"
nerdfontDisplayName: "CaskaydiaMono Nerd Font"
emailPersonal: "nv.canh@outlook.com"
emailWork: "vancanh.ng@samsung.com"

# Termux
phoneUserName: "u0_a505"
tabletUserName: "u0_a353"
phoneDeviceName: "bunnies-f741b"
tabletDeviceName: "bunnies-x826b"

# Local ip address
desktopIPv4: 192.168.0.100
laptopIPv4: 192.168.0.101
phoneIPv4: 192.168.0.102

# Work ip address
workIPv4Lan: 107.98.39.128
workIPv4Wifi: 107.98.68.201

# Tailscale
tailnetDNS: "walleye-godzilla.ts.net"
bunniesDesktopIP: 100.99.0.0
bunniesDesktopDebianIP: 100.99.0.1
bunniesF741bIP: 100.99.0.2
bunniesX826bIP: 100.99.0.3
bunniesLaptopDebianIP: 100.99.0.4

# Proxy settings
androidSerial: "R32X6003EPL"
proxyIP: "127.0.0.1"
proxyPort: "3128"
proxyServer: "http://127.0.0.1:3128"
workNoProxy: "localhost,127.0.0.1,::1,.sec.samsung.net,.samsung.net,.corp.samsungelectronics.net,sts.secsso.net,.mediatek.com,.figma.com,107.98.0.0/16,107.113.0.0/16"
