fullName: "Ngô Văn Cảnh"
nickName: "Michael"
userName: "canh25xp"
themeName: "Catppuccin"
themeFlavor: "Mocha"
themeAccent: "Pink"
nerdfontName: "CaskaydiaMonoNerdFont-Regular.ttf"
nerdfontDisplayName: "CaskaydiaMono Nerd Font"
