import = [
  "~/AppData/Roaming/alacritty/catppuccin-mocha.toml"
]

[window]
startup_mode = "Maximized"

[shell]
program = "pwsh.exe"
# args = [ "-wd ~" ]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 12

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "Return", mods = "Control|Shift", action = "Open" },
  { key = "W", mods = "Control|Shift", action = "Quit" },
  { key = "Slash", mods = "Control", chars = "\u001B[47;5u" },
  { key = "Space", mods = "Control", chars = "\u0000" }
]
