import = [
  # uncomment the flavour you want below:
  "~/AppData/Roaming/alacritty/catppuccin-mocha.toml"
]

[window]
startup_mode = "Maximized"

[shell]
program = "pwsh.exe"
# args = [ "-wd ~" ]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 12

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
