notARepository: skip
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: "3"
  showBottomLine: false
  border: single
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
    rate: 100
git:
  parseEmoji: true
