[manager]
prepend_keymap = [
  { on = "<C-a>", run = 'my-fev-command1', desc = "Just for test!" },
  { on = "?", run = 'help', desc = "Open help" },
]
append_keymap = [
  { on = [ "g", "a" ], run = 'my-fev-command2', desc = "Just for test!" },
]
