[manager]
prepend_keymap = [
  { on = "<C-a>", run = 'my-fev-command1', desc = "Just for test!" },
  { on = "?", run = 'help', desc = "Open help" },
  { on = "T", run = 'plugin toggle-pane min-preview', desc = "Toggle Preview" },
  { on = "f", run = 'plugin jump-to-char', desc = "Jump to char" },
]
append_keymap = [
  { on = [ "g", "a" ], run = 'my-fev-command2', desc = "Just for test!" },
]
