[mgr]
prepend_keymap = [
  { on = "<C-a>", run = 'toggle_all --state=on', desc = "Select all" },
  { on = "?", run = 'help', desc = "Open help" },
  { on = "T", run = 'plugin toggle-pane min-preview', desc = "Toggle Preview" },
  { on = "f", run = 'plugin jump-to-char', desc = "Jump to char" },
  { on = [ "g", "l" ], run = 'shell "DumpstateViewer -logcatViewer %0"', desc = "Open with logcat" },
]
append_keymap = [
  { on = [ "g", "a" ], run = 'my-fev-command2', desc = "Just for test!" },
]
