[mgr]
show_hidden = true
sort_dir_first = true
show_symlink = true

[preview]
image_delay = 100
max_width  = 1000
max_height = 1000

[opener]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'vlc %*', orphan = true, for = "windows" },
]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*", block = true, for = "windows" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
