# --- Access control ---
acl allowed_client src 107.98.39.128/32
acl allowed_client src 107.98.68.201/32

# Allow only these clients
http_access allow allowed_client
http_access deny all

# --- Logging (human-readable time) ---
logformat readable %{%Y-%m-%d %H:%M:%S}tl %>a %Ss/%03>Hs %<st %rm %ru %Sh/%<A
access_log stdio:/var/log/squid/access.log readable

# --- Caching ---
cache_log /var/log/squid/cache.log
cache_dir ufs /var/spool/squid 10000 16 256
