"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 3000

[cmd_duration]
min_time = 1000
show_milliseconds = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
truncate_to_repo = false

[package]
disabled = true

[container]
disabled = true

[git_metrics]
disabled = false

[battery]
disabled = true
