"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
truncate_to_repo = false

[package]
disabled = true

[container]
disabled = true

[git_metrics]
disabled = false

[battery]
disabled = true
