# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
notARepository: skip
promptToReturnFromSubprocess: true
git:
  autoFetch: false
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  nerdFontsVersion: "3"
  showBottomLine: true
  skipStashWarning: true
  scrollHeight: 1
  border: rounded
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
    rate: 100
  theme: # https://github.com/catppuccin/lazygit/blob/main/themes/mocha/pink.yml
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
