# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
# https://github.com/catppuccin/lazygit/blob/main/themes/mocha/pink.yml
notARepository: skip
promptToReturnFromSubprocess: false
git:
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"
  showBottomLine: false
  scrollHeight: 1
  border: single
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
    rate: 100
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'

